### ISSUE TITLE
Reused variable?

### ISSUE THREAD

**Issue by dbhurley** [anagrambuild/mobile-pwa-with-passkey-wallet#3]
Is this correct?

https://github.com/anagrambuild/mobile-pwa-with-passkey-wallet/blob/50cab54509121d807aba769352819aba2fe56ae8/shared/db/schema.ts#L13

**Comment by johnrjj** [comment]
Should be: 
```
 turnkey_user_id: varchar('turnkey_user_id', { length: 191 }),
```

Will fix, thank you! I think I had just forgotten to fix the schema after manually fixing the db.

**Comment by dbhurley** [comment]
I suspected, wasn't sure with external vs internal ID, I would love to connect? x?

**Comment by johnrjj** [comment]
Fixed here -- https://github.com/anagrambuild/mobile-pwa-with-passkey-wallet/commit/2d31f9090effddad1ef2dfd1cda010f8d68144f4

Absolutely -- will reach out on X/Twitter! :)
