### ISSUE TITLE
Attacked- the binaries have been swapped.

### ISSUE THREAD

**Issue by PandaS7S** [anagrambuild/mobile-pwa-with-passkey-wallet#4]
<img width="832" alt="Screenshot 2023-10-24 at 10 02 05 PM" src="https://github.com/anagrambuild/mobile-pwa-with-passkey-wallet/assets/75605308/ffb03ba0-9313-4850-a291-35561c31df71">
Pls see attachement.

It is suspected that the binaries files that are relied upon during installation have been replaced. 

dependency has some probs

**Comment by PandaS7S** [comment]
@johnrjj @austbot pls review as no assignees.

**Comment by johnrjj** [comment]
Hey @PandaS7S -- I'll check with the Turnkey engineering team, we don't control that brew package.

In the meantime, to get the Turnkey CLI installed, there's a few options here based on the trust assumption levels you need: 
https://github.com/tkhq/tkcli#moderate-trust -- you should be able to install via git and a make script locally.

**Comment by johnrjj** [comment]
Turnkey team is looking into the homebrew SHA mismatch.

**Comment by johnrjj** [comment]
Fixed -- it was just a release issue, everything is fine and should now work! Thanks for reporting!
